### ISSUE TITLE
On a specific crash

### ISSUE THREAD

**Issue by Sunconure11** [DreamCraft-Tech/HMCL_Remade#1]
https://github.com/DreamCraft-Tech/HMCL_Remade/blob/fd116e3d35a201d2e643add016e7d17ac1f1553f/HMCLCore/src/test/resources/logs/fabric-version-0.12.txt

Did you ever find a resolution to this?

**Comment by Sunconure11** [comment]
@DreamUniverse843

**Comment by DreamUniverse843** [comment]
It can be run sucessfully with fabric 0.12.12 on Minecraft 1.18.1 , however I haven't tested other versions cause it's for my server's cilent and my server uses 1.18.1

**Comment by Sunconure11** [comment]
Found my culprits.
